rails/one/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  #root 'home#index'
  root 'friends#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails/one/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/one/app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

rails/one/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

rails/one/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails/one/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.frinds.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

rails/one/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "My name is dreth"
    about_me
  end
end

rails/one/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/one/app/helpers/friends_helper.rb
module FriendsHelper
end

rails/one/app/helpers/home_helper.rb
module HomeHelper
end

rails/one/app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="card">
  <div class="card-body">
    <div class="field form-group">
      <%= form.text_field :first_name, class:"form-control", placeholder:"First name" %>
    </div>

    <div class="field form-group">
      <%= form.text_field :last_name, class:"form-control", placeholder:"Last name" %>
    </div>

    <div class="field form-group">
      <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
    </div>

    <div class="field form-group">
      <%= form.text_field :phone, class:"form-control", placeholder:"Phone number" %>
    </div>

    <div class="field form-group">
      <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
    </div>

    <div class="field form-group">
      <%= form.number_field :user_id, id: :friend_user_id,  class:"form-control", value:current_user.id, type: :hidden %>
    </div>

    <br/>
    <div class="actions">
      <%= form.submit class:"btn btn-secondary" %>
    </div>
  </div>
</div>

<% end %>

rails/one/app/views/friends/edit.html.erb
<h1>Editing Friend</h1>
<br/>
<%= render 'form', friend: @friend %>
<br/>
<%= link_to 'Show', @friend, class:"btn btn-secondary" %>
<%= link_to 'Back', friends_path, class:"btn btn-dark"  %>
<%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class"btn btn-danger" %>

rails/one/app/views/friends/index.html.erb
<% if user_signed_in?%>

  <h1>Friend list</h1>

  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user%>
        <tr>
          <td><%= link_to "#{friend.first_name} #{friend.last_name}", friend %></td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>
<% else %>
  <h1>Hello world!</h1>
  <p>First rails page!</p>
<% end %>

rails/one/app/views/friends/new.html.erb
<h1>Add new Friend</h1>
<br/>
<%= render 'form', friend: @friend %>
<br/>
<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

rails/one/app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %> <%= @friend.last_name %>
  </h1>

  <p>
    <%= @friend.email %> | <%= @friend.phone %> | <%= @friend.twitter %>
  </p>

  <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary" %>
  <%= link_to 'Back', friends_path, class:"btn btn-dark" %>
  <%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class"btn btn-danger" %>
</div>

rails/one/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Friend list app', root_path, class:"navbar-brand" %>
  
  <div class="navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'About Us', home_about_path, class:"nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Edit profile', edit_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Add friend', new_friend_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

rails/one/app/views/home/about.html.erb
<h1>About me</h1>

<p><%= @about_me %></p>

rails/one/app/views/home/index.html.erb
<h1>Hello world!</h1>
<p>First rails page!</p>

rails/one/app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%= notice %></strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

rails/one/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# bootstrap stylesheet%>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <%# bootstrap bundle with popper%>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

  </head>

  <body>

    <%= render 'home/header' %>
    <div class="container">
      </br>
      <% if notice %>
        <%= render 'layouts/alert'%>
      <% end %>
        <%= yield %>
    </div>
  </body>
</html>